import Head from "next/head";
import Image from "next/image";
import skulls from "../public/skulls.jpeg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Teknoland-production, Techno vinyls and digital music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full h-screen">
        <h1 className="mb-5 text-3xl text-emerald-700">Teknoland Production</h1>
        <div className="relative w-60 h-60">
          <Image
            src={skulls}
            alt="skulls"
            layout="fill"
            objectFit="cover"
            className="rounded-full"
            priority
          />
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
